# Generated by Django 5.2.3 on 2025-06-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_Name', models.CharField(max_length=60)),
                ('type_category', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_image', models.ImageField(null=True, upload_to='')),
                ('product_price', models.IntegerField()),
                ('product_description', models.TextField()),
                ('product_type', models.ManyToManyField(to='main.producttype')),
            ],
        ),
    ]
